apiVersion: apps/v1
kind: Deployment
metadata:
  name: uuid-deployment
  labels:
    app: uuid
spec:
  template:
    metadata:
      name: uuid-generator
      labels:
        app: uuid-generator

    spec:
      containers:
      - name: uuid-container
        image: pranit039/uuid-generator:v20240614
        ports:
        - containerPort: 8080
  replicas: 3
  selector:
    matchLabels:
      app: uuid-generator
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
  




